### ISSUE TITLE
Avatar for team members

### ISSUE THREAD

**Issue by andre-code** [triarc/website#15]
- [ ] research if there is any cool avatar solution

https://getavataaars.com/
https://www.southpark.de/info/lv0nha/avatar
https://ichbingelb.de/?gclid=Cj0KCQiA962BBhCzARIsAIpWEL2AfBjv2L9vvcvccZwIOxs6l7RgR-MEbuSTJTXwqGgw975qYq2oV9MaArktEALw_wcB

- Suggestion nerd mode different avatar

**Comment by no0dles** [comment]
created with SDFX in the appstore

<img width="636" alt="Screenshot 2021-03-11 at 17 51 51" src="https://user-images.githubusercontent.com/14818450/110823707-aa5d2800-8292-11eb-8343-37514ed68429.png">
<img width="634" alt="Screenshot 2021-03-11 at 17 52 00" src="https://user-images.githubusercontent.com/14818450/110823718-acbf8200-8292-11eb-8187-43513f3aeae0.png">
<img width="624" alt="Screenshot 2021-03-11 at 17 52 17" src="https://user-images.githubusercontent.com/14818450/110823729-ae894580-8292-11eb-8bb9-a80dddd69fc4.png">
<img width="623" alt="Screenshot 2021-03-11 at 17 51 15" src="https://user-images.githubusercontent.com/14818450/110823797-ba750780-8292-11eb-865b-da62a3488c7b.png">
<img width="588" alt="Screenshot 2021-03-11 at 17 51 27" src="https://user-images.githubusercontent.com/14818450/110823808-bd6ff800-8292-11eb-84ac-5a22d770361e.png">
